<?php

########################################################################
# Extension Manager/Repository config file for ext: "pxa_newsletter_subscription"
#
# Auto generated by Extension Builder 2012-12-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'Newsletter Subscription',
    'description' => 'Newsletter Subscription',
    'category' => 'plugin',
    'author' => 'Inna Titorenko, Daniel Lorenz',
    'author_email' => 'inna@pixelant.se, daniel.lorenz@tritum.de',
    'author_company' => 'Pixelant, TRITUM GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '6.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.9.99',
            'php' => '7.2.0-7.2.999'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
