<?php

########################################################################
# Extension Manager/Repository config file for ext: "pxa_newsletter_subscription"
#
# Auto generated by Extension Builder 2012-12-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'Newsletter Subscription',
    'description' => 'Newsletter Subscription',
    'category' => 'plugin',
    'author' => 'Pixelant',
    'author_email' => 'info@pixelant.net',
    'author_company' => 'Pixelant',
    'state' => 'stable',
    'clearCacheOnLoad' => false,
    'version' => '10.0.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.1.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
